build: Add dependabot config file
CheesecakeLabs/django-drf-boilerplate pull request #152
Opened 2020-08-28 19:39 UTC by rodolfolottin

2020-08-28 19:54 UTC, fredericojordan requested changes
By using the root folder `/` instead of the `requirements/`, we leave out `requirements/dev.txt`, which is not listed on the root `requirements.txt`

2020-08-28 19:54 UTC, fredericojordan commented on .github/dependabot.yml
> +    directory: "/"
```suggestion
    directory: "requirements/"
```

2020-08-28 20:01 UTC, rodolfolottin commented
@fredericojordan thanks!

2020-08-31 10:51 UTC, fredericojordan approved these changes

2020-08-31 11:47 UTC, rkpinheiro approved these changes

2020-08-31 11:57 UTC, natamvo approved these changes

2020-08-31 14:13 UTC, gustavuka approved these changes

2020-08-31 14:22 UTC, matpfernandes approved these changes

2020-09-01 14:27 UTC, merged