cklauth authentication app
CheesecakeLabs/django-drf-boilerplate pull request #19
Opened 2017-02-28 19:01 UTC by joaoricardo000

The first version of our authentication app, using django-allauth and django-rest-auth.  
It adds two new sets of urls:  
- cklauth/urls.py
Template rendered views for authentication  (allauth)
  
- cklauth/api/v1/urls.py
API views for authentication  (rest-auth)
  
The auth urls follow this pattern:  
`http://app.com/auth/*` (templates)
`http://app.com/api/v1/auth/*` (api)

The default settings.py uses email instead of username as parameter for login.  
There is endpoints for Facebook login, as social login example, with template and API views.  
Besides the urls, there is also a templates folder with allauth default templates, for customization of views and emails.

2017-02-28 20:25 UTC, enapupe commented on .gitignore
> +.idea/
gitignore should only contain files generated by the project, not developer's..

2017-02-28 21:56 UTC, jonatasbaldin commented on .gitignore
> +.idea/
Why? I don't think so. Better then accidentally adding IDE's files all over the git project.

2017-02-28 21:56 UTC, jonatasbaldin commented
I'm gonna take a look soon!

2017-02-28 22:21 UTC, enapupe commented on .gitignore
> +.idea/
You should add your IDE files to your custom gitignore. To to EVERY project you may come to work with.

2017-03-01 12:58 UTC, enapupe commented on .gitignore
> +.idea/
You should add your IDE files to your custom gitignore. Otherwise you'd have to add it to all projects you may come to work with.

2017-03-01 13:05 UTC, joaoricardo000 commented on .gitignore
> +.idea/
Neat, didn't know that.  
https://git-scm.com/docs/gitignore
Just had to add the personal ignores here:`$HOME/.config/git/ignore`

2017-03-01 13:15 UTC, jonatasbaldin commented on .gitignore
> +.idea/
Neat. Apologies. You rock. I suck.

❤️

2017-03-01 13:19 UTC, enapupe commented on .gitignore
> +.idea/
Or add this to your global `.gitconfig`:
```
[core]
excludesfile = ~/.gitignore_global
```

2017-03-01 13:33 UTC, dleitee approved these changes

2017-03-02 15:23 UTC, jonatasbaldin requested changes
I think we still need two things here:
* Tests for this endpoints (as they are from external packages, we may not need to test it, but rather add a test CI to make sure its indeed being tested).
* Documentation for each endpoint.

2017-03-10 05:25 UTC, smaniotto reviewed
I just added some code style notes on the templates, but not sure if everybody agrees if my points actually.

Regarding tests: I think both libraries have a good coverage, it would be over-testing in my opinion, we could spend time elsewhere.

Regarding docs: agree that we should add docs whenever a new endpoint is created, but we haven't decided a docs format yet. Then I think we can get back to it when we have something.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/base.html
> +
Extra blank line here 😬

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/account_inactive.html
> +<p>{% trans "This account is inactive." %}</p>
Normally I use indentation with templates as well:
```
{% block content %}
  <h1>{% trans "Account Inactive" %}</h1>

  <p>{% trans "This account is inactive." %}</p>
{% endblock %}
```

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/email.html
> +<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>
Indentation as well.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/email.html
> +      <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked"{%endif %} value="{{emailaddress.email}}"
Excessive spaces for indentation (6). We can use either 2 or 4 on HTML indentation, your call since you're first :)

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/email.html
> +{% endblock %}
Overall I'd fix indentations and remove extra blank-lines.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/email_confirm.html
> +{% endblock %}
Here too, I think it's easier to read with indentation.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/login.html
> +{% endblock %}
Indentation and consistency between 2 vs 4 spaces for it.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/logout.html
> +{% endblock %}
Indentation inside block and 2 vs 4 spaces for indentation as well.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/messages/password_changed.txt
> +
Remove blank line.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/messages/password_set.txt
> +
Remove blank line.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/signup.html
> +{% endblock %}
Indentation inside block and consistency between 2 vs 4 spaces for indentation.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/signup_closed.html
> +{% endblock %}
Indentation inside block.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/verification_sent.html
> +
Remove blank line.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/password_reset.html
> +
Remove blank line.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/account/verified_email_required.html
> +{% endblock %}
Indentation and extra blank lines.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/admin/base_site.html
> +</style>
Remove blank style tags.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/admin/base_site.html
> +<h1 id="site-name">Cheesecake Project Admin</h1>
Indentation.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/base.html
> +</html>
Indentation inside block and if tags and consistency between 2 or 4 spaces for indentations.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/openid/login.html
> +{% endblock %}
Indentation inside block.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/socialaccount/authentication_error.html
> +{% endblock %}
Indentation.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/socialaccount/base.html
> +
Remove blank line.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/socialaccount/connections.html
> +{% endblock %}
Indentation.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/socialaccount/login_cancelled.html
> +{% endblock %}
Indentation.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/socialaccount/signup.html
> +{% endblock %}
Indentation and keep consistency between 2 and 4 spaces.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/socialaccount/snippets/login_extra.html
> +
Remove blank line.

2017-03-10 05:25 UTC, smaniotto commented on project_name/templates/socialaccount/snippets/provider_list.html
> +
Extra blank line at bottom, 2 space indentation and indentation inside tags.

2017-03-10 15:05 UTC, jonatasbaldin commented
Agree on @smaniotto's syntax style.

Also agree on tests and docs, but will say that this should be the next thing to do: implement a code coverage check and a way to document the API, before other endpoints. I guess I will do this next Tuesday.

2017-03-10 15:05 UTC, jonatasbaldin approved these changes

2017-03-10 15:27 UTC, merged