Update comments in flake8 config file regarding char limits
CheesecakeLabs/django-drf-boilerplate pull request #34
Opened 2018-09-03 13:45 UTC by gdevincenzi

2018-09-03 14:05 UTC, rodolfolottin commented
Let's seize this opportunity and set it using `max-line-length=120`. We all know that common sense is not enough.

2018-09-03 14:07 UTC, phsetti commented on .flake8
> +  # Just use common sense and keep it around 100-120
You could use something like `max-line-length = 120` here.

2018-09-03 14:07 UTC, phsetti approved these changes

2018-09-03 14:17 UTC, gdevincenzi commented
Let me clarify a little bit then:
@rodolfolottin warned me that my linter wasn't checking for line length. I did check that it wasn't and asked @smaniotto why not, and decided to add his reply to the comment in the code.

2018-09-03 14:19 UTC, gdevincenzi commented
I think the spirit of it is that you should `hover around` those numbers, but no need to make big adjustments if you went a couple chars above the limit.

Like @smaniotto said to me, we will just end up discussing something that is not that important. No one is writing one liners of 200+ chars, right?

What do you guys think?

2018-09-03 14:23 UTC, rodolfolottin commented
We are all complaining about the lack of patterns that we have here at cheesecake; whether frontend, backend and mobile. IMHO defining it is one step ahead in resolving this problem.

2018-09-03 17:22 UTC, dleitee approved these changes

2018-09-03 17:39 UTC, fredericojordan commented
I'm with the `max-line-length = 120` bandwagon!

2018-09-03 17:41 UTC, fredericojordan requested changes
I'd rather just have a limit set, as people have mentioned before.

2018-09-05 14:14 UTC, gdevincenzi commented
I don't mind having this limit set, if that's what we all agree on.

2018-09-05 14:31 UTC, gdevincenzi commented
@fredericojordan @rodolfolottin @phsetti @dleitee @smaniotto @douglasgimli @urataki @karranb 

Since it seems like there is consensus around the 120 limit, I've changed this commit to reflect that.

If no one disagrees, let's push this change forward.

2018-09-05 17:34 UTC, fredericojordan approved these changes

2018-09-05 17:34 UTC, fredericojordan commented
:shipit:

2018-09-05 17:35 UTC, dleitee approved these changes

2018-09-05 18:08 UTC, rodolfolottin commented
:shipit:

2018-09-05 18:08 UTC, rodolfolottin approved these changes

2018-09-05 21:11 UTC, merged